# Generated by Django 5.1.4 on 2025-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_aluno_estudante_remove_frequencia_pessoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='RA',
            new_name='ra',
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='Turma',
            new_name='turma',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
